imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@WFPlatformBundle/Resources/config/sonata_config.yml" }


# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOSUser Configuration
fos_user:
    db_driver:  orm
    firewall_name:  main
    user_class: WF\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
    registration:
        form:
            type: app_user_registration

#Sonata
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ...

# PUGXMULTI UserBundle

pugx_multi_user:
    users:
        freelancer:
            entity: 
                class: WF\UserBundle\Entity\Freelancer
            registration:
                form: 
                    type: WF\UserBundle\Form\Type\RegistrationFreelancerFormType
                    name: fos_user_registration_form
                    validation_groups:  [Registration, Default]
                template: WFUserBundle:Registration:freelancer.form.html.twig
            profile:
                form:
                    type: WF\UserBundle\Form\Type\ProfileFreelancerFormType
                    name: fos_user_profile_form
                    validation_groups:  [Profile, Default] 

        client:
            entity: 
                class: WF\UserBundle\Entity\Client
            registration:
                form: 
                    type: WF\UserBundle\Form\Type\RegistrationClientFormType
                    name: fos_user_registration_form
                    validation_groups:  [Registration, Default]
                template: WFUserBundle:Registration:client.form.html.twig
            profile:
                form: 
                    type: WF\UserBundle\Form\Type\ProfileClientFormType
                    name: fos_user_profile_form
                    validation_groups:  [Profile, Default]
        recruteur:
            entity: 
                class: WF\UserBundle\Entity\Recruteur
            registration:
                form: 
                    type: WF\UserBundle\Form\Type\RegistrationRecruteurFormType
                    name: fos_user_registration_form
                    validation_groups:  [Registration, Default]
                template: WFUserBundle:Registration:recruteur.form.html.twig
            profile:
                form: 
                    type: WF\UserBundle\Form\Type\ProfileRecruteurFormType
                    name: fos_user_profile_form
                    validation_groups:  [Profile, Default]  
