wf_core:
    resource: "@WFCoreBundle/Resources/config/routing.yml"
    prefix:   /

wf_platform:
    resource: "@WFPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile


fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
freelancer_registration:
    path:  /register/freelancer
    defaults: { _controller: WFUserBundle:RegistrationFreelancer:register }

client_registration:
    path:  /register/client
    defaults: { _controller: WFUserBundle:RegistrationClient:register }

recruteur_registration:
    path:  /register/recruteur
    defaults: { _controller: WFUserBundle:RegistrationRecruteur:register }

wf_user_profile:
    resource: "@WFUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

User:
    resource: "@WFUserBundle/Controller"
    type:     annotation
Platform:
    resource: "@WFPlatformBundle/Controller"
    type:     annotation



