security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        WF\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_CLIENT: [ROLE_USER] 
        ROLE_FREELANCER: [ROLE_USER]
        ROLE_RECRUTEUR: [ROLE_USER]
        ROLE_ADMIN:       [ROLE_SONATA_ADMIN,ROLE_USER, ROLE_FREELANCER,ROLE_RECRUTEUR,ROLE_CLIENT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern: ^/login$
            anonymous: true
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_provider: security.csrf.token_manager
                default_target_path: wf_user_profile_wall
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                key:    %secret%


    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client, roles: ROLE_CLIENT }
        - { path: ^/freelancer, roles: ROLE_FREELANCER }
        - { path: ^/recruteur, roles: ROLE_RECRUTEUR }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }