fos_user:
    db_driver: orm
    firewall_name: main
    user_class: WF\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager

pugx_multi_user:
    users:
        freelancer:
            entity: 
                class: WF\UserBundle\Entity\Freelancer
            registration:
                form: 
                    type: WF\UserBundle\Form\Type\RegistrationFreelancerFormType
                    name: fos_user_registration_form
                    validation_groups:  [Registration, Default]
                template: WFUserBundle:Registration:freelancer.form.html.twig
            profile:
                form:
                    type: WF\UserBundle\Form\Type\ProfileFreelancerFormType
                    name: fos_user_profile_form
                    validation_groups:  [Profile, Default] 

        client:
            entity: 
                class: WF\UserBundle\Entity\Client
            registration:
                form: 
                    type: WF\UserBundle\Form\Type\RegistrationClientFormType
                    name: fos_user_registration_form
                    validation_groups:  [Registration, Default]
                template: WFUserBundle:Registration:client.form.html.twig
            profile:
                form: 
                    type: WF\UserBundle\Form\Type\ProfileClientFormType
                    name: fos_user_profile_form
                    validation_groups:  [Profile, Default] 