<?php

namespace WF\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends EntityRepository
{
	public function getOffres($page,$nbPerPage)
	{
		$query = $this->createQueryBuilder('o')
		
		    ->Join('o.projet', 'p')
		    ->addSelect('p')
		    ->where('o.projet.id = p.id')
			->orderBy('o.dateDepo','DESC')
			->getQuery()
			;
			$query
				->setFirstResult(($page-1)*$nbPerPage)
				->setMaxResults($nbPerPage)
				;

			return new Paginator($query,true) ;
    }

    public function getOffresOfProjet($pId)
    {
		$em = $this->getEntityManager();
		$query = $em->createQuery(
		'SELECT o
		FROM WFPlatformBundle:Offre o
		WHERE o.projet = :pId'
		)->setParameter('pId', $pId);

		$offres = $query->getResult();
		return $offres;
    }
}
