<?php

namespace WF\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends EntityRepository
{

	public function getLast($user)
	{
		/*$query = $this->createQueryBuilder('p')
		    ->addSelect('p')
		    ->addSelect('p.questions.length nbrQsts')
			->orderBy('p.id','DESC')
			->setMaxResults(3)
			->getQuery();*/
		$em = $this->getEntityManager();
		$query = $em->createQuery(
		    'SELECT t
		    FROM WFPlatformBundle:Test t
		    WHERE t.recruteur = :recruteur
		    ORDER BY t.id DESC')
		->setParameter('recruteur', $user)
		->setMaxResults(3);

		return $query->getResult();
		
	}

	public function findAllValid()
	{
		$em = $this->getEntityManager();
		$query = $em->createQuery(
		    'SELECT t
		    FROM WFPlatformBundle:Test t
		    WHERE t.verified = 1
		    ORDER BY t.id DESC');

		return $query->getResult();

	}


}
